name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  ProtobufDumper:
    name: ProtobufDumper 

    runs-on: ubuntu-latest

    # https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build ProtobufDumper
      run: dotnet build --configuration Release Resources/ProtobufDumper/ProtobufDumper.sln
        
    - name: Upload ProtobufDumper
      uses: actions/upload-artifact@v4
      with:
        name: ProtobufDumper
        path: 'Resources/ProtobufDumper/bin/Release/*'


